VERSION 1
ID 138
REFERENCE SABERMENUS
COUNT 4
INDEX 0
{
   REFERENCE TEAM_SIZE
   TEXT_LANGUAGE1 "Team Size:"
   TEXT_LANGUAGE2 "Team Size:"
   TEXT_LANGUAGE3 "Team Size:"
}
INDEX 1
{
   REFERENCE FOLLOW
   TEXT_LANGUAGE1 "Follow"
   TEXT_LANGUAGE2 "Follow"
   TEXT_LANGUAGE3 "Follow"
}
INDEX 2
{
   REFERENCE REMOVE
   TEXT_LANGUAGE1 "Remove"
   TEXT_LANGUAGE2 "Remove"
   TEXT_LANGUAGE3 "Remove"
}
INDEX 3
{
   REFERENCE BEGIN_VOTE_TO_REMOVE
   TEXT_LANGUAGE1 "Begin vote to remove this player"
   TEXT_LANGUAGE2 "Begin vote to remove this player"
   TEXT_LANGUAGE3 "Begin vote to remove this player"
}