VERSION 1
REFERENCE SABERMENUS
COUNT 2
INDEX 0
{
   REFERENCE TEAM_SIZE
   TEXT_LANGUAGE1 "Team Size:"
   TEXT_LANGUAGE2 "Team Size:"
   TEXT_LANGUAGE3 "Team Size:"
}
INDEX 1
{
   REFERENCE FOLLOW
   TEXT_LANGUAGE1 "Follow"
   TEXT_LANGUAGE2 "Follow"
   TEXT_LANGUAGE3 "Follow"
}